version: '3'

services:
  mitsuba:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: mitsuba
    container_name: mitsuba
    volumes:
      - ../src:/workspace/src
      - ../scene:/workspace/scene
    working_dir: /workspace
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
